"""
Command Builder Module for grandMA2

This module provides high-level functions to construct grandMA2 command strings.
These functions are responsible only for generating correctly formatted commands,
not for sending them.

According to coding-standards.md, these functions are "thin wrappers" that
only construct MA commands without any Telnet logic.

=============================================================================
grandMA2 Keyword Classification
=============================================================================

The grandMA2 command line syntax follows these general rules:
- Basic syntax: [Function] [Object]
- All objects have a default function which is used if no function is given.
- Most functions have a default object or object type.
- Objects are arranged in a hierarchical tree structure.

Keywords are classified into three types:

1. HELPING KEYWORDS (Prepositions/Conjunctions)
   - Used to create relations between functions and objects
   - Examples: At, Thru, +, If, While

2. OBJECT KEYWORDS (Nouns)
   - Used to allocate objects in your show file
   - Usually used with numbers, IDs, names, and labels
   - Examples: Fixture, Channel, Group, Preset, Cue, Sequence, Executor

3. FUNCTION KEYWORDS (Verbs)
   - Perform a task or function
   - Often followed by objects to which the function applies
   - Some functions are global and don't need objects (e.g., Blackout)
   - Examples: Store, Delete, Copy, Goto, Clear, Label, SelFix

=============================================================================
"""

# Constants
from .constants import (
    PRESET_TYPES,
    STORE_BOOL_OPTIONS,
    STORE_FLAG_OPTIONS,
    STORE_VALUE_OPTIONS,
)

# Object Keywords
from .objects import (
    attribute,
    channel,
    cue,
    cue_part,
    dmx,
    dmx_universe,
    executor,
    # Executor Object Keywords
    fader,
    fader_page,
    button_page,
    channel_fader,
    channel_page,
    exec_button_1,
    exec_button_2,
    exec_button_3,
    all_button_executors,
    all_chase_executors,
    all_fader_executors,
    all_seq_executors,
    # Misc Object Keywords
    camera,
    channel_link,
    filter_keyword,
    fixture_type,
    form,
    gel,
    image,
    item_3d,
    layer,
    macro,
    mask,
    master,
    master_fade,
    media_server,
    menu,
    message,
    messages,
    model,
    plugin,
    pm_area,
    profile,
    protocol,
    root,
    screen,
    search_result,
    selection,
    special_master,
    surface,
    user,
    user_profile,
    value_keyword,
    view,
    view_button,
    view_page,
    world,
    feature,
    fixture,
    group,
    layout,
    preset,
    preset_type,
    sequence,
    timecode,
    timecode_slot,
    timer,
)

# Function Keywords
from .functions import (
    # Assign Function Keyword
    assign,
    assign_fade,
    assign_function,
    assign_macro_cmd,
    assign_to_layout,
    empty,
    temp_fader,
    # Label Function Keyword
    label,
    label_sequence_cue,
    # Appearance Function Keyword
    appearance,
    # At Function Keyword
    at,
    at_full,
    at_zero,
    attribute_at,
    channel_at,
    executor_at,
    fixture_at,
    group_at,
    preset_type_at,
    # Edit Function Keyword
    edit,
    # Cut Function Keyword
    cut,
    # Paste Function Keyword
    paste,
    # Copy Function Keyword
    copy,
    copy_cue,
    # Move Function Keyword
    move,
    # Delete Function Keyword
    delete,
    delete_cue,
    delete_fixture,
    delete_group,
    delete_messages,
    delete_preset,
    # Remove Function Keyword
    remove,
    remove_effect,
    remove_fixture,
    remove_preset_type,
    remove_selection,
    # List Function Keyword
    list_objects,
    list_attribute,
    list_cue,
    list_group,
    list_messages,
    list_preset,
    # Info Function Keyword
    info,
    info_cue,
    info_group,
    info_preset,
    # Macro Placeholder
    macro_with_input_after,
    macro_with_input_before,
    # Helping Keywords (Plus +, Minus -, And, If)
    add_to_selection,
    at_relative,
    condition_and,
    if_condition,
    page_next,
    page_previous,
    remove_from_selection,
    # Park Function Keywords
    park,
    unpark,
    # Call Function Keywords
    call,
    # Variable Function Keywords
    set_user_var,
    set_var,
    add_user_var,
    add_var,
    # Blind & Preview Function Keywords
    blind,
    blind_edit,
    preview,
    preview_edit,
    # Blackout & Global State Function Keywords
    blackout,
    black,
    freeze,
    highlight,
    full_highlight,
    solo,
    # Cue Timing Function Keywords
    delay,
    out_delay,
    fade,
    out_fade,
    # Fixture Control Function Keywords
    align,
    all_keyword,
    fix,
    locate,
    next_keyword,
    previous,
    invert,
    # Executor Control Function Keywords
    off,
    on,
    kill,
    flash,
    swop,
    stomp,
    temp,
    toggle,
    release,
    top,
    select,
    # Programmer & Show Data Function Keywords
    block,
    unblock,
    clone,
    default,
    extract,
    insert,
    record,
    replace,
    update,
    oops,
    # Intensity & Misc Function Keywords
    full,
    to_full,
    zero,
    to_zero,
    load,
    learn,
    # Crossfade Function Keywords
    crossfade,
    crossfade_a,
    crossfade_b,
    manual_xfade,
    # Rate & Speed Function Keywords
    rate,
    rate1,
    double_rate,
    half_rate,
    double_speed,
    half_speed,
    speed,
    # MAtricks Function Keywords
    matricks,
    matricks_blocks,
    matricks_filter,
    matricks_groups,
    matricks_interleave,
    matricks_reset,
    matricks_wings,
    # Effect Function Keywords
    effect,
    effect_attack,
    effect_bpm,
    effect_decay,
    effect_delay,
    effect_fade,
    effect_form,
    effect_high,
    effect_hz,
    effect_id,
    effect_low,
    effect_phase,
    effect_sec,
    effect_speed_group,
    effect_width,
    sync_effects,
    # System Management Keywords
    backup,
    black_screen,
    cmd_delay,
    cmd_help,
    delete_show,
    escape,
    exit_keyword,
    help_keyword,
    load_show,
    lock,
    login,
    logout,
    new_show,
    normal,
    reboot,
    reload_plugins,
    restart,
    save_show,
    select_drive,
    set_hostname,
    set_ip,
    set_network_speed,
    setup,
    shutdown,
    tools,
    unlock,
    version,
    # Network/Session Keywords
    change_dest,
    chat,
    disconnect_station,
    drop_control,
    end_session,
    invite_station,
    join_session,
    leave_session,
    network_info,
    network_node_info,
    network_node_update,
    network_speed_test,
    remote,
    remote_command,
    take_control,
    telnet,
    web_remote_prog_only,
    # Extended List Keywords
    list_effect_library,
    list_fader_modules,
    list_library,
    list_macro_library,
    list_oops,
    list_owner,
    list_plugin_library,
    list_shows,
    list_update,
    list_user_var,
    list_var,
    # Advanced Edit Keywords
    align_fader_modules,
    all_rows,
    auto_create,
    circular_copy,
    export_keyword,
    flip,
    identify_fader_module,
    import_keyword,
    interleave,
    remove_individuals,
    shuffle_selection,
    shuffle_values,
    # Conditional/Flow Keywords
    end_if,
    if_active,
    if_output,
    if_prog,
    or_keyword,
    with_keyword,
    # Navigation Keywords
    agenda,
    alert,
    down,
    load_next,
    load_prev,
    move_3d,
    next_row,
    preview_executor,
    prev_row,
    rotate_3d,
    search,
    up,
    # Show Data Keywords
    crash_log_copy,
    crash_log_delete,
    crash_log_list,
    lua,
    psr,
    psr_list,
    psr_prepare,
    reset_dmx_selection,
    reset_guid,
    thru,
    update_firmware,
    update_software,
    update_thumbnails,
    # RDM Keywords
    rdm_automatch,
    rdm_autopatch,
    rdm_fixture_type,
    rdm_info,
    rdm_list,
    rdm_set_parameter,
    rdm_setpatch,
    rdm_unmatch,
    # MIDI Keywords
    midi_control,
    midi_note,
    midi_program,
    # Step Timing Function Keywords
    snap_percent,
    step_fade,
    step_in_fade,
    step_out_fade,
    fade_path,
    # Flash/Swop Extension Function Keywords
    flash_go,
    flash_on,
    swop_go,
    swop_on,
    store_look,
    # Other Function Keywords
    call_preset,
    clear,
    clear_active,
    clear_all,
    clear_selection,
    def_go_back,
    def_go_forward,
    def_go_pause,
    go,
    go_back,
    go_back_executor,
    go_executor,
    go_fast_back,
    go_fast_forward,
    go_macro,
    go_sequence,
    goto,
    goto_cue,
    label_group,
    label_preset,
    pause_sequence,
    select_fixture,
    select_group,
    store,
    store_cue,
    store_group,
    store_preset,
)

__all__ = [
    # Constants
    "PRESET_TYPES",
    "STORE_FLAG_OPTIONS",
    "STORE_BOOL_OPTIONS",
    "STORE_VALUE_OPTIONS",
    # Object Keywords
    "attribute",
    "feature",
    "fixture",
    "channel",
    "group",
    "layout",
    "preset",
    "preset_type",
    "cue",
    "cue_part",
    "sequence",
    "executor",
    # Executor Object Keywords
    "fader",
    "fader_page",
    "button_page",
    "channel_fader",
    "channel_page",
    "exec_button_1",
    "exec_button_2",
    "exec_button_3",
    "all_button_executors",
    "all_chase_executors",
    "all_fader_executors",
    "all_seq_executors",
    # Misc Object Keywords
    "camera",
    "channel_link",
    "filter_keyword",
    "fixture_type",
    "form",
    "gel",
    "image",
    "item_3d",
    "layer",
    "macro",
    "mask",
    "master",
    "master_fade",
    "media_server",
    "menu",
    "message",
    "messages",
    "model",
    "plugin",
    "pm_area",
    "profile",
    "protocol",
    "root",
    "screen",
    "search_result",
    "selection",
    "special_master",
    "surface",
    "user",
    "user_profile",
    "value_keyword",
    "view",
    "view_button",
    "view_page",
    "world",
    "dmx",
    "dmx_universe",
    "timecode",
    "timecode_slot",
    "timer",
    # Assign Function Keyword
    "assign",
    "assign_fade",
    "assign_function",
    "assign_macro_cmd",
    "assign_to_layout",
    "empty",
    "temp_fader",
    # Label Function Keyword
    "label",
    # Appearance Function Keyword
    "appearance",
    # At Function Keyword
    "at",
    "at_full",
    "at_zero",
    "attribute_at",
    "fixture_at",
    "channel_at",
    "group_at",
    "executor_at",
    "preset_type_at",
    # Edit Function Keyword
    "edit",
    # Cut Function Keyword
    "cut",
    # Paste Function Keyword
    "paste",
    # Copy Function Keyword
    "copy",
    "copy_cue",
    # Move Function Keyword
    "move",
    # Macro Placeholder (@ Character)
    "macro_with_input_after",
    "macro_with_input_before",
    # Other Function Keywords
    "store",
    "store_cue",
    "store_group",
    "store_preset",
    "select_fixture",
    "clear",
    "clear_selection",
    "clear_active",
    "clear_all",
    "label_group",
    "label_preset",
    "label_sequence_cue",
    # Delete Function Keyword
    "delete",
    "delete_cue",
    "delete_fixture",
    "delete_group",
    "delete_messages",
    "delete_preset",
    # Remove Function Keyword
    "remove",
    "remove_effect",
    "remove_fixture",
    "remove_preset_type",
    "remove_selection",
    # List Function Keyword
    "list_objects",
    "list_attribute",
    "list_cue",
    "list_group",
    "list_messages",
    "list_preset",
    # Info Function Keyword
    "info",
    "info_cue",
    "info_group",
    "info_preset",
    # Go
    "go",
    "go_executor",
    "go_macro",
    # GoBack
    "go_back",
    "go_back_executor",
    # Goto
    "goto",
    # Go/Pause/Goto (Legacy)
    "go_sequence",
    "pause_sequence",
    "goto_cue",
    # GoFast (<<< and >>>)
    "go_fast_back",
    "go_fast_forward",
    # DefGo (Selected Executor)
    "def_go_back",
    "def_go_forward",
    "def_go_pause",
    # Helping Keywords (Plus +, Minus -, And, If)
    "at_relative",
    "add_to_selection",
    "remove_from_selection",
    "page_next",
    "page_previous",
    "condition_and",
    "if_condition",
    # Park Function Keywords
    "park",
    "unpark",
    # Call Function Keywords
    "call",
    # Variable Function Keywords
    "set_user_var",
    "set_var",
    "add_user_var",
    "add_var",
    # Blind & Preview Function Keywords
    "blind",
    "blind_edit",
    "preview",
    "preview_edit",
    # Blackout & Global State Function Keywords
    "blackout",
    "black",
    "freeze",
    "highlight",
    "full_highlight",
    "solo",
    # Cue Timing Function Keywords
    "delay",
    "out_delay",
    "fade",
    "out_fade",
    # Fixture Control Function Keywords
    "align",
    "all_keyword",
    "fix",
    "locate",
    "next_keyword",
    "previous",
    "invert",
    # Executor Control Function Keywords
    "off",
    "on",
    "kill",
    "flash",
    "swop",
    "stomp",
    "temp",
    "toggle",
    "release",
    "top",
    "select",
    # Programmer & Show Data Function Keywords
    "block",
    "unblock",
    "clone",
    "default",
    "extract",
    "insert",
    "record",
    "replace",
    "update",
    "oops",
    # Intensity & Misc Function Keywords
    "full",
    "to_full",
    "zero",
    "to_zero",
    "load",
    "learn",
    # Crossfade Function Keywords
    "crossfade",
    "crossfade_a",
    "crossfade_b",
    "manual_xfade",
    # Rate & Speed Function Keywords
    "rate",
    "rate1",
    "double_rate",
    "half_rate",
    "double_speed",
    "half_speed",
    "speed",
    # Step Timing Function Keywords
    "snap_percent",
    "step_fade",
    "step_in_fade",
    "step_out_fade",
    "fade_path",
    # Flash/Swop Extension Function Keywords
    "flash_go",
    "flash_on",
    "swop_go",
    "swop_on",
    "store_look",
    # MAtricks Function Keywords
    "matricks",
    "matricks_blocks",
    "matricks_filter",
    "matricks_groups",
    "matricks_interleave",
    "matricks_reset",
    "matricks_wings",
    # Effect Function Keywords
    "effect",
    "effect_attack",
    "effect_bpm",
    "effect_decay",
    "effect_delay",
    "effect_fade",
    "effect_form",
    "effect_high",
    "effect_hz",
    "effect_id",
    "effect_low",
    "effect_phase",
    "effect_sec",
    "effect_speed_group",
    "effect_width",
    "sync_effects",
    # System Management Keywords
    "backup",
    "black_screen",
    "cmd_delay",
    "cmd_help",
    "delete_show",
    "escape",
    "exit_keyword",
    "help_keyword",
    "load_show",
    "lock",
    "login",
    "logout",
    "new_show",
    "normal",
    "reboot",
    "reload_plugins",
    "restart",
    "save_show",
    "select_drive",
    "set_hostname",
    "set_ip",
    "set_network_speed",
    "setup",
    "shutdown",
    "tools",
    "unlock",
    "version",
    # Network/Session Keywords
    "change_dest",
    "chat",
    "disconnect_station",
    "drop_control",
    "end_session",
    "invite_station",
    "join_session",
    "leave_session",
    "network_info",
    "network_node_info",
    "network_node_update",
    "network_speed_test",
    "remote",
    "remote_command",
    "take_control",
    "telnet",
    "web_remote_prog_only",
    # Extended List Keywords
    "list_effect_library",
    "list_fader_modules",
    "list_library",
    "list_macro_library",
    "list_oops",
    "list_owner",
    "list_plugin_library",
    "list_shows",
    "list_update",
    "list_user_var",
    "list_var",
    # Advanced Edit Keywords
    "align_fader_modules",
    "all_rows",
    "auto_create",
    "circular_copy",
    "export_keyword",
    "flip",
    "identify_fader_module",
    "import_keyword",
    "interleave",
    "remove_individuals",
    "shuffle_selection",
    "shuffle_values",
    # Conditional/Flow Keywords
    "end_if",
    "if_active",
    "if_output",
    "if_prog",
    "or_keyword",
    "with_keyword",
    # Navigation Keywords
    "agenda",
    "alert",
    "down",
    "load_next",
    "load_prev",
    "move_3d",
    "next_row",
    "preview_executor",
    "prev_row",
    "rotate_3d",
    "search",
    "up",
    # Show Data Keywords
    "crash_log_copy",
    "crash_log_delete",
    "crash_log_list",
    "lua",
    "psr",
    "psr_list",
    "psr_prepare",
    "reset_dmx_selection",
    "reset_guid",
    "thru",
    "update_firmware",
    "update_software",
    "update_thumbnails",
    # RDM Keywords
    "rdm_automatch",
    "rdm_autopatch",
    "rdm_fixture_type",
    "rdm_info",
    "rdm_list",
    "rdm_set_parameter",
    "rdm_setpatch",
    "rdm_unmatch",
    # MIDI Keywords
    "midi_control",
    "midi_note",
    "midi_program",
    # Backward Compatibility Aliases
    "select_group",
    "call_preset",
]
